# Generated by Django 3.2.1 on 2021-05-05 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_createblog_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='createblog',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='createblog',
            name='title',
            field=models.CharField(choices=[('django', 'Django'), ('html', 'HTML'), ('css', 'CSS'), ('js', 'JS'), ('python', 'Python'), ('android', 'Android')], default='djnago', max_length=7),
        ),
    ]
