# Generated by Django 3.2.1 on 2021-05-05 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210505_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='createblog',
            name='cat',
            field=models.CharField(choices=[('django', 'Django'), ('html', 'HTML'), ('css', 'CSS'), ('js', 'JS'), ('python', 'Python'), ('android', 'Android')], default='djnago', max_length=7),
        ),
        migrations.AlterField(
            model_name='createblog',
            name='title',
            field=models.CharField(max_length=20),
        ),
    ]
