# Generated by Django 3.2.1 on 2021-05-05 11:45

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210505_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createblog',
            name='content',
            field=tinymce.models.HTMLField(verbose_name='Content'),
        ),
    ]
