# Generated by Django 3.2.1 on 2021-05-06 12:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_createblog_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='createblog',
            name='short_des',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='createblog',
            name='cat',
            field=models.CharField(choices=[('Django', 'Django'), ('Html', 'HTML'), ('CSS', 'CSS'), ('JS', 'JS'), ('Python', 'Python'), ('Android', 'Android')], default='Djnago', max_length=7),
        ),
    ]
