# Generated by Django 3.2.2 on 2021-05-07 16:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_createblog_short_des'),
    ]

    operations = [
        migrations.AddField(
            model_name='createblog',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='createblog',
            name='slug',
            field=models.SlugField(max_length=250, unique=True),
        ),
    ]
